spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-morning-thunder-a11ga3j2-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7hMzwSLk8JaU

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true