spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/budgeting_app
spring.datasource.username=JB
spring.datasource.password=Fuck1ng!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true